### PR TITLE
test decorator for cpu and cuda

### LINKED ISSUE #72: unittesting device agnostic code
Some of the code is giving issues when running on cuda devices and I was thinking whether we could have device testing integrated in unittests. 

To highligth some things, backproject_fourier is not running with cuda tensors and I noticed @rsanchezgarc also pointed out some issues in PR #54.

Running all the tests with both tensors on cpu and a cuda device would of course solve it. However, if there would be automated testing for PR's in the future, the default GitHub instances do not support this. Secondly, nice about pytorch is that it also allows development on a CPU only system and still have portability for GPUs.

I was looking online, cause I imagined more people need this, and found that torch supports a 'meta' device: https://pytorch.org/torchdistx/latest/fake_tensor.html . Also see the discussion here (https://github.com/pytorch/pytorch/issues/61654). I don't know whether its fully supported throughout pytorch, but I could play around with it and see how applicable it is.

For example though, the following produces appropriate errors:
```
>>> import torch
>>> a = torch.zeros((10,10))  # default will initialize on 'cpu'
>>> b = torch.zeros((10,10), device='meta')
>>> c = a * b
RuntimeError: Tensor on device meta is not on the expected device cpu!
```

### PR DESCRIPTION
**Pull request by McHaillet**
Preface: maybe a bit void seeing your other message now, but was fun to mess around with still

Overview of changes:

- Added a test decorator to run tests on both devices 'cpu' and 'cuda'. It tried with the 'meta' device, but it was too much of a hassle. I don't think torch has a good option yet to do this. Some ideas: we could make a switch to run tests only on CPU for people without a GPU. Or for M1 chips specifically could use this device: https://pytorch.org/docs/master/notes/mps.html. Other thought: Maybe the decorator just runs on all available devices?
- I add the decorator to all tests and ran them, for some things I made some fixes to run on both devices.
- Found out midway I did not set up pre-commit properly. I then had to update the pre-commit config and fix some rules for new versions of packages. Sorry about that.

BTW also noticed that 'projection' and 'rescaling' are lacking unittests.

Closes #72

### CODE REVIEW

**Comment by McHaillet** [comment]
> Other thought: Maybe the decorator just runs on all available devices?

Decided to add this in.

**Comment by McHaillet** [comment]
Would it be possible to make the tests check for differentiability for deep-learning?

**Comment by alisterburt** [comment]
this is really wondeful @McHaillet - great work 🙂

> What would prevent us from releasing a version 0.1 of a libtilt API and putting it on pypi? Maybe add a short text on what the project intention is and a docs page with api. But this is a bit clashing with the individual packages.

I agree this is one path forwards and did consider it myself, the questions I was asking myself when thinking about it were:
1. is this the best path for getting the functionality out to people
2. am I happy with the API

I ended up deciding that small standalone packages would be better on both fronts - the thing that will bring them together and make it feel coherent/cohesive is a nice teamtomo.org which points at their associated docs (which don't exist yet 🤣 )

I'll merge this anyway and will absolutely be adding this to all of those packages. I would love the differentiability tests too but don't know how I would do that immediately, do you have ideas?

Does this make sense to you? Would you like to work together on getting the libtilt functionality into teamtomo as isolated packages? This feels like the equivalent of the v0.1 API you were imagining and it would be great to have someone else excited about the effort 🙂

**Review by alisterburt — APPROVED** [review]

**Comment by McHaillet** [comment]
I am not immediately convinced (but I trust you have good ideas on the topic) maybe you could help me see your points?

My main two concerns:

**1**
Although I fully agree with the teamtomo philo about modular, reusable components, I would say having all these image proc. functions in one place does fulfill this. It's all build on the same torch framework (and some numpy/scipy) which for me makes sense to have in one place. 

For a developer that wants to depend on this library, it is also not a huge codebase, i.e. the dependency is fully overshadowed by pytorch. Rather having to add all these individual dependencies seems more tedious. 

**2**
From a POV of developing the library itself, it seems easier to have these things in one place, or at least some parts. As an example: 
- frequency grids seem to belong together with ctf/dose-filters/bandpass. 
- coordinate grids, interpolation, transformations all seem logical to have together.

It would be difficult to first have to go to another package to fix something for CTF's that is due to an issue in frequency grids.

I can see it imposes a hurdle to develop a big library, but it also is a big hurdle if you have to move through different packages and learn how these components tie in together.

I can see the benefit of some splitting but would still be more inclined to keep it one place. If you think splitting is really needed, perhaps some components can still be kept together.

**Comment by McHaillet** [comment]
I could see though that if we can for example ensure that the grid-utils API (https://github.com/alisterburt/torch-grid-utils/tree/main) remains consistent, it makes it easier to have it as a dependency.

**Comment by McHaillet** [comment]
> I'll merge this anyway and will absolutely be adding this to all of those packages. I would love the differentiability tests too but don't know how I would do that immediately, do you have ideas?

Not not immediately, but it should be possible right? You just need to check that the gradients can be calculated from input to output. I don't think its possible as a decorator though.

**Comment by McHaillet** [comment]
> Does this make sense to you? Would you like to work together on getting the libtilt functionality into teamtomo as isolated packages? This feels like the equivalent of the v0.1 API you were imagining and it would be great to have someone else excited about the effort 🙂

For sure down to work together on it! However, my contract is almost finished and I don't know yet where I will be after. For now definitely happy to think along :)

**Pull request merged**
